apiVersion: v1
kind: ConfigMap
metadata:
  name: derp-grafana-config
  namespace: derp
data:
  derp-config: |
    apiVersion: 1

    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://derp-loki-svc:3100
        jsonData:
          timeout: 60
          maxLines: 1000
      
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://derp-prometheus-svc:9090
        jsonData:
          timeInterval: "15s"

      - name: Zipkin
        type: zipkin
        url: http://derp-zipkin-svc:9411
        access: proxy
