apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: derp-db-pvc-pr-$PULL_REQUEST_ID
  namespace: $NAMESPACE
spec:
  accessModes:
  - ReadWriteOnce
  #- ReadWriteMany
  resources:
    requests:
      storage: 1Gi
