    apiVersion: 1

    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        jsonData:
          timeout: 60
          maxLines: 1000
      
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        jsonData:
          timeInterval: "15s"

      # - name: Zipkin
      #   type: zipkin
      #   url: http://zipkin:9411
      #   access: proxy
